In [1]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn import svm
import pandas as pd
from sklearn.metrics import accuracy_score
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
upload=pd.read_csv('upload.csv')
train.head()
print(train.keys())
print(train.shape)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')
(8000, 14)


One hot
=====

In [2]:
# One-Hot encoding 
list_cat = ['Geography', 'Gender']
train_onehot = pd.get_dummies(train, columns = list_cat, prefix = list_cat)
test_onehot=pd.get_dummies(test,columns=list_cat,prefix=list_cat)
display(test_onehot.head())
display(train_onehot.head())

RowNumber  CustomerId      Surname  CreditScore  Age  Tenure    Balance  \
0       2209    15623595        Scott          726   39       3   62397.41   
1       9924    15740283     Yegorova          661   42       3  130339.64   
2       4617    15802368          Tan          545   34       6   62397.41   
3       6077    15615322  Anayochukwu          731   42       3   86717.08   
4       9240    15766374       Glover          533   50       6   62397.41   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0              1          0               0        106139.31   
1              1          1               0        125776.38   
2              2          1               1         78372.28   
3              1          1               0        136026.27   
4              1          1               1        135205.58   

   Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                 1                  0                0              1   
1                 1                  0                0              0   
2                 1                  0                0              0   
3                 0                  0                1              1   
4                 1                  0                0              1   

   Gender_Male  
0            0  
1            1  
2            1  
3            0  
4            0

RowNumber  CustomerId     Surname  CreditScore  Age  Tenure    Balance  \
0        551    15806307   Trevisano          720   38       5  114051.97   
1       6897    15709621      Martin          682   54       4   62397.41   
2       4588    15619340      Palmer          672   31       5  119903.67   
3        291    15620746  Napolitani          592   40       4  104257.86   
4       1673    15646372         Yao          753   42       5  120387.73   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              2          0               1        107577.29       0   
1              1          1               0        113088.60       1   
2              1          1               1        132925.17       0   
3              1          1               0        110857.33       0   
4              1          0               1        126378.57       0   

   Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                 0                  0                1              0   
1                 1                  0                0              1   
2                 1                  0                0              1   
3                 0                  0                1              1   
4                 0                  0                1              0   

   Gender_Male  
0            1  
1            0  
2            0  
3            0  
4            1

刪掉無關的編號值
=====

In [3]:
train_set = train_onehot.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
test_set=test_onehot.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
display(train_set.head())
display(test_set.head())

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          720   38       5  114051.97              2          0   
1          682   54       4   62397.41              1          1   
2          672   31       5  119903.67              1          1   
3          592   40       4  104257.86              1          1   
4          753   42       5  120387.73              1          0   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        107577.29       0                 0   
1               0        113088.60       1                 1   
2               1        132925.17       0                 1   
3               0        110857.33       0                 0   
4               1        126378.57       0                 0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                1              0            1  
1                  0                0              1            0  
2                  0                0              1            0  
3                  0                1              1            0  
4                  0                1              0            1

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          726   39       3   62397.41              1          0   
1          661   42       3  130339.64              1          1   
2          545   34       6   62397.41              2          1   
3          731   42       3   86717.08              1          1   
4          533   50       6   62397.41              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               0        106139.31                 1                  0   
1               0        125776.38                 1                  0   
2               1         78372.28                 1                  0   
3               0        136026.27                 0                  0   
4               1        135205.58                 1                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                0              0            1  
2                0              0            1  
3                1              1            0  
4                0              1            0

In [4]:
features=list(train_set.drop(columns=['Exited']))
target='Exited'
display(features)

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Geography_France',
 'Geography_Germany',
 'Geography_Spain',
 'Gender_Female',
 'Gender_Male']

標準化
========

In [5]:
sc=StandardScaler()

#標準化
train_set[features]=sc.fit_transform(train_set[features])
display(train_set)

#標準化
test_set[features]=sc.transform(test_set[features])
display(test_set)

CreditScore       Age    Tenure   Balance  NumOfProducts  HasCrCard  \
0        1.509906 -0.663721  0.339933  0.428978       0.799546  -1.537586   
1        0.866637  1.465241 -0.445812 -1.214512      -0.917139   0.650370   
2        0.697356 -1.595141  0.339933  0.615161      -0.917139   0.650370   
3       -0.656894 -0.397600 -0.445812  0.117359      -0.917139   0.650370   
4        2.068534 -0.131480  0.339933  0.630562      -0.917139  -1.537586   
...           ...       ...       ...       ...            ...        ...   
7995    -1.063169 -1.062901  1.125677  0.652575       0.799546   0.650370   
7996    -0.487612  0.267700  1.911421  1.440568      -0.917139   0.650370   
7997     0.815853  0.001580  0.339933  1.025801      -0.917139   0.650370   
7998     1.425266 -0.663721 -0.445812  0.577801      -0.917139  -1.537586   
7999    -0.521469 -0.131480  0.339933 -1.214512      -0.917139  -1.537586   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0           0.966801         0.304927       0         -1.001501   
1          -1.034339         0.529787       1          0.998501   
2           0.966801         1.339115       0          0.998501   
3          -1.034339         0.438752       0         -1.001501   
4           0.966801         1.072015       0         -1.001501   
...              ...              ...     ...               ...   
7995        0.966801         1.011302       1          0.998501   
7996       -1.034339        -0.033763       0         -1.001501   
7997       -1.034339         1.251627       1         -1.001501   
7998       -1.034339        -0.188456       0          0.998501   
7999       -1.034339        -1.378566       0          0.998501   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0             -0.580814         1.746019      -0.911178     0.911178  
1             -0.580814        -0.572731       1.097481    -1.097481  
2             -0.580814        -0.572731       1.097481    -1.097481  
3             -0.580814         1.746019       1.097481    -1.097481  
4             -0.580814         1.746019      -0.911178     0.911178  
...                 ...              ...            ...          ...  
7995          -0.580814        -0.572731       1.097481    -1.097481  
7996           1.721720        -0.572731       1.097481    -1.097481  
7997          -0.580814         1.746019       1.097481    -1.097481  
7998          -0.580814        -0.572731      -0.911178     0.911178  
7999          -0.580814        -0.572731       1.097481    -1.097481  

[8000 rows x 14 columns]

CreditScore       Age    Tenure   Balance  NumOfProducts  HasCrCard  \
0        1.611475 -0.530660 -1.231556 -1.214512      -0.917139  -1.537586   
1        0.511147 -0.131480 -1.231556  0.947201      -0.917139   0.650370   
2       -1.452516 -1.195961  1.125677 -1.214512       0.799546   0.650370   
3        1.696115 -0.131480 -1.231556 -0.440735      -0.917139   0.650370   
4       -1.655653  0.933001  1.125677 -1.214512      -0.917139   0.650370   
...           ...       ...       ...       ...            ...        ...   
1995    -0.047481 -1.062901  1.125677 -1.214512       0.799546   0.650370   
1996     0.138728 -0.264540  0.339933 -0.076837       0.799546   0.650370   
1997    -1.401731  0.400760 -1.231556  0.588901       0.799546   0.650370   
1998    -0.487612  0.134640  1.911421 -1.214512       0.799546   0.650370   
1999    -0.267547 -1.462081  0.339933  0.159119      -0.917139   0.650370   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0          -1.034339         0.246258          0.998501          -0.580814   
1          -1.034339         1.047446          0.998501          -0.580814   
2           0.966801        -0.886631          0.998501          -0.580814   
3          -1.034339         1.465639         -1.001501          -0.580814   
4           0.966801         1.432155          0.998501          -0.580814   
...              ...              ...               ...                ...   
1995        0.966801        -0.159220          0.998501          -0.580814   
1996       -1.034339         0.384664         -1.001501           1.721720   
1997        0.966801         0.678179          0.998501          -0.580814   
1998        0.966801         1.143716         -1.001501          -0.580814   
1999       -1.034339         0.164698         -1.001501           1.721720   

      Geography_Spain  Gender_Female  Gender_Male  
0           -0.572731       1.097481    -1.097481  
1           -0.572731      -0.911178     0.911178  
2           -0.572731      -0.911178     0.911178  
3            1.746019       1.097481    -1.097481  
4           -0.572731       1.097481    -1.097481  
...               ...            ...          ...  
1995        -0.572731      -0.911178     0.911178  
1996        -0.572731      -0.911178     0.911178  
1997        -0.572731       1.097481    -1.097481  
1998         1.746019       1.097481    -1.097481  
1999        -0.572731       1.097481    -1.097481  

[2000 rows x 13 columns]

RBF
=======

In [9]:
#rbf
mysvm=svm.SVC(kernel='rbf',gamma=0.04,C=0.85)
mysvm.fit(train_set[features],train_set[target])
predict_rbf=mysvm.predict(test_set[features])
display(predict_rbf)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
upload_rbf=upload
upload_rbf['Excited']=predict_rbf
upload_rbf.to_csv('uploadrbf.csv')

POLY
=======

In [23]:
#POLY
mysvm1=svm.SVC(kernel='poly',gamma=0.04,C=0.85)
mysvm1.fit(train_set[features],train_set[target])
predict_poly=mysvm1.predict(test_set[features])
display(predict_poly)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
upload_poly=upload
upload_poly['Exited']=predict_poly
upload_poly.to_csv('uploadpoly.csv')

SIGMOID
===========

In [27]:
mysvm2=svm.SVC(kernel='sigmoid',gamma=0.05,C=0.87)
mysvm2.fit(train_set[features],train_set[target])
predict_sigmoid=mysvm2.predict(test_set[features])
display(predict_sigmoid)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
upload_sigmoid=upload
upload_sigmoid['Exited']=predict_poly
upload_sigmoid.to_csv('uploadsigmoid.csv')